### ISSUE TITLE
Add Support for H6104, H605C, H6199

### ISSUE THREAD

**Issue by EdenNelson** [Bluetooth-Devices/govee-ble#63]
Govee API only supports RGB light functionality, so Govee TV LED Backlight with cameras and addressable RGB strips like H6104, H605C, H6199, etc require local Bluetooth support to switch to modes besides color like video, music, etc.

![IMG_9024](https://user-images.githubusercontent.com/16840996/229369558-75d72646-fb86-4948-bb0a-8b3c8445f1a7.JPG)
![IMG_9023 (1)](https://user-images.githubusercontent.com/16840996/229369562-0cc3fa04-076b-48ba-a5dd-e897e41fcd6d.JPG)

**Comment by amaciuc** [comment]
Why did you close this issue?

It would be a nice feature and I also look forward to it if it could be implemented.

**Comment by TobiTenno** [comment]
I also agree, @EdenNelson, could you just give a brief reason?

**Comment by EdenNelson** [comment]
I decommissioned the devices because of poor integration support and the no response from the govee ble developers on this issue. If I no longer have the devices, I won’t be able to support the developers’ testing if/when they write the code. The devices are 'tweeners, so, unsurprisingly, they are unsupported. Please feel free to copy my issue and reopen it.

**Comment by TobiTenno** [comment]
I ended up using the mqtt govee integration that worked out pretty well
