### ISSUE TITLE
H5100 reports in Govee app but stopped in HA

### ISSUE THREAD

**Issue by Supermankal718** [Bluetooth-Devices/govee-ble#64]
**Describe the bug**
4 of my 6 H5100 have become unavailable in the past few weeks in HA. They were connected with no issues and were reporting perfectly for weeks. Then out of nowhere some of them were no longer connected to HA even though they are connected in the Govee app and to the thermo gateway. 

**Additional context**
I have updated HA multiple times since the issue and reloaded the integration with no fix. The temperature settings have all stayed in the same location since they were first connected and I have even changed the batteries still won't show in HA.

**Comment by bdraco** [comment]
This device wasn't officially supported. It just happened to "mostly" work before

https://github.com/Bluetooth-Devices/govee-ble/releases/tag/v0.30.0
