### ISSUE TITLE
Support for H5104 / H5174

### ISSUE THREAD

**Issue by m42cel** [Bluetooth-Devices/govee-ble#70]
**Is your feature request related to a problem? Please describe.**
Currently the [compatibility list](https://www.home-assistant.io/integrations/govee_ble#supported-devices) doesn't include the H5104 and H5174.

Looking at the [Theengs Decoder](https://github.com/theengs/decoder) it seems like H5100/01/02/04/74/77 all use the same message format:
* https://github.com/theengs/decoder/blob/5860102de4f44eafeb4a8577963e89e52c53b373/src/devices/H5102_json.h
* https://github.com/theengs/decoder/pull/424

It would be great if all those would be supported, too.

**Describe the solution you'd like**
From my shallow analysis it looks like the model codes only have to be added to the if statement in [parser.py](https://github.com/Bluetooth-Devices/govee-ble/blob/0e534622cf484422e783fd38a65320708133e403/src/govee_ble/parser.py#L150) for it to work (but I might also miss something here).

**Comment by bdraco** [comment]
If you have these devices please turn on debug logging for the bluetooth integration in Home Assistant and provide the AdvertisementData

**Comment by m42cel** [comment]
I currently do not own these but I was considering buying the H5104 over the H5075 because they are currently on sale and a bit cheaper.
Since I need a few more hygrometers I might just order one of the currently unsupported H5104 along with a few H5075 to provide the needed information and help integrating them into Home Assistant. I would be really glad if I could help adding support for another model. I might just need a few hints on how to create a dev build for validating.

**Comment by kramttocs** [comment]
The 5104 already works. I have two connected via bluetooth proxies. They showed up less than a second after putting in the batteries.

**Comment by kramttocs** [comment]
If it matters to update the 'Model' shown in the UI, the H5104 is showing under:  device_type = "H5101/H5102/H5177"

**Comment by m42cel** [comment]
My devices arrived today and I can also confirm that the H5104 works like a charm. Thanks for adapting the model numbers and the documentation of the supported devices. :)
