### ISSUE TITLE
Add H5105 Hygrometer Thermometer to Supported Devices

### ISSUE THREAD

**Issue by Norrodar** [Bluetooth-Devices/govee-ble#78]
**Is your feature request related to a problem? Please describe.**
The Govee H5105 is not on the list of supported devices.

**Describe the solution you'd like**
List Govee H5105 as supported.

**Additional context**
I just ordered 6 times the Govee H5105 and they seem to work fine. Putted in the battery and the appeared in Auto-Discover and sending data. They are showing up as H5101 / H5102 / H5177

![300949845-b43c9a1e-5247-424d-96ed-299559214baa](https://github.com/Bluetooth-Devices/govee-ble/assets/551636/a8bf946a-74be-4889-a687-7bf77f700741)

**Comment by bdraco** [comment]
https://github.com/Bluetooth-Devices/govee-ble/releases/tag/v0.29.0
